#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
	external_bar all:0:0 \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_shadow off \
	window_opacity on \
	window_opacity_duration 0.0 \
	window_animation_duration 0.1 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.9 \
	window_border on \
	window_border_hidpi on \
	window_border_blur on \
	window_border_width 2 \
	window_border_radius 12 \
	active_window_border_color 0xFFa6e3a1 \
	normal_window_border_color 0xFFf5c2e7 \
	insert_feedback_color 0xfff9e2af \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	mouse_modifier ctrl \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	layout bsp \
	top_padding 12 \
	bottom_padding 12 \
	left_padding 12 \
	right_padding 12 \
	window_gap 12

yabai -m rule --add app="^System Settings$" sticky=on manage=off layer=above
yabai -m rule --add app="^Finder$" sticky=on manage=off layer=above
yabai -m rule --add app="^Activity Monitor$" manage=off layer=above
yabai -m rule --add app="Raycast" sticky=on manage=off layer=above
yabai -m rule --add app="DeepL" sticky=on manage=off layer=above
yabai -m rule --add app="zoom.us" manage=off opacity=1.0 layer=above
yabai -m rule --add app="1Password" manage=off layer=above
yabai -m rule --add app="Zalo" sticky=on manage=off layer=above
yabai -m rule --add app="LINE" sticky=on manage=off layer=above
yabai -m rule --add app="Karabiner-Elements" sticky=on manage=off layer=above
yabai -m rule --add app="Karabiner-EventViewer" sticky=on manage=off layer=above
yabai -m rule --add app="OrbStack" manage=off layer=above
yabai -m rule --add app="Music" manage=off layer=above
yabai -m rule --add app="Podcasts" manage=off layer=above
yabai -m rule --add app="^Microsoft .*" manage=off layer=above
yabai -m rule --add app="NordVPN" manage=off layer=above
yabai -m rule --add app="App Store" manage=off layer=above
yabai -m rule --add app="^Arc$" title="^Space [0-9]+" manage=off mouse_follows_focus=off layer=above
yabai -m rule --add app="^Arc$" title="^$" manage=off mouse_follows_focus=off layer=above
yabai -m rule --add app="Preview" manage=off layer=above
yabai -m rule --add app="CompareMerge" manage=off layer=above
yabai -m rule --add app="waiwai" manage=off layer=above
yabai -m signal --add event=application_front_switched action="yabai -m window --layer normal"

echo "yabai configuration loaded.."

borders active_color=0xFFa6e3a1 inactive_color=0xFFf5c2e7 width=4.0 2>/dev/null 1>&2 &
